apiVersion: v1
kind: Service
metadata:
  name: todo-app-postgres-service
  namespace: todo-app
  labels:
    app: todo-app
    component: database
spec:
  selector:
    app: todo-app
    component: database
  ports:
    - name: postgres
      port: 5432 # ClusterIP Service Port
      targetPort: 5432 # Container Port
  
